name: Build Lite RTTrading
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install PyQt6 PyQt6-WebEngine pyinstaller
          # Download UPX for compression
          choco install upx

      - name: Build Optimized EXE
        run: |
          pyinstaller --noconsole --onefile --clean --upx-dir "C:\ProgramData\chocolatey\lib\upx\tools\upx-4.2.4-win64" `
          --exclude-module PyQt6.QtSql `
          --exclude-module PyQt6.QtTest `
          --exclude-module PyQt6.QtXml `
          --exclude-module tkinter `
          --name "RTTrading" main.py

      - name: Upload Smallest Build
        uses: actions/upload-artifact@v4
        with:
          name: RTTrading-UltraLite
          path: dist/RTTrading.exe
